apiVersion: v1
kind: Secret
metadata:
  name: k3s-default
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    my.org/cluster: internal    # external
type: Opaque
stringData:
  name: k3s.localhost
  server: https://kubernetes.default.svc